apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: letsencryptit-renew
spec:
  schedule: "30 9,21 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: letsencryptit
            image: index.docker.io/larssb/letsencryptit
            env:
            - name: CERT_NAME
              valueFrom:
                secretKeyRef: 
                  key: CERT_NAME
                  name: letsencryptit
            - name: CERT_DESCRIPTION
              valueFrom:
                secretKeyRef:
                  key: CERT_DESCRIPTION
                  name: letsencryptit
            - name: dns_cloudflare_api_key
              valueFrom:
                secretKeyRef:
                  key: dns_cloudflare_api_key
                  name: letsencryptit
            - name: dns_cloudflare_email
              valueFrom:
                secretKeyRef:
                  key: dns_cloudflare_email
                  name: letsencryptit
            - name: LETSENCRYPT_DATA_DIR
              valueFrom:
                secretKeyRef:
                  key: LETSENCRYPT_DATA_DIR
                  name: letsencryptit
            - name: gcp_project_name
              valueFrom:
                secretKeyRef:
                  key: gcp_project_name
                  name: letsencryptit
            - name: gcp_project_proxy
              valueFrom:
                secretKeyRef:
                  key: gcp_project_proxy
                  name: letsencryptit
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secret/GOOGLE_APPLICATION_CREDENTIALS.json
            volumeMounts:
            - name: letsencryptdata
              mountPath: "/data"
            - name: secret
              mountPath: "/secret"
              readOnly: true
          volumes:
            - name: letsencryptdata
              persistentVolumeClaim:
                claimName: bs-letsencrypt-disk
            - name: secret
              secret:
                defaultMode: 0400
                secretName: letsencryptit                
          restartPolicy: OnFailure