kind: Pod
apiVersion: v1
metadata:
  name: letsencryptit-cli
  labels:
    app: letsencryptit-cli 
spec:
  containers:
    - name: letsencryptit-cli
      image: index.docker.io/larssb/letsencryptit
      args:
        - |-
          -c
          import time
          while True:
              print('.')
              time.sleep(5)
      env:
      - name: CERT_NAME
        valueFrom:
          secretKeyRef: 
            key: CERT_NAME
            name: letsencryptit
      - name: dns_cloudflare_api_key
        valueFrom:
          secretKeyRef:
            key: dns_cloudflare_api_key
            name: letsencryptit
      - name: dns_cloudflare_email
        valueFrom:
          secretKeyRef:
            key: dns_cloudflare_email
            name: letsencryptit
      - name: LETSENCRYPT_DATA_DIR
        valueFrom:
          secretKeyRef:
            key: LETSENCRYPT_DATA_DIR
            name: letsencryptit
      - name: GOOGLE_APPLICATION_CREDENTIALS
        valueFrom:
          secretKeyRef:
            key: GOOGLE_APPLICATION_CREDENTIALS
            name: letsencryptit
      volumeMounts:
      - name: letsencryptdata
        mountPath: "/data"
  volumes:
    - name: letsencryptdata
      persistentVolumeClaim:
        claimName: bs-letsencrypt-disk