kind: Pod
apiVersion: v1
metadata:
  name: letsencryptit-cli
  labels:
    app: letsencryptit-cli 
spec:
  containers:
    - name: letsencryptit-cli
      image: index.docker.io/larssb/letsencryptit
      command: ["/bin/sh", "-c"]
      args:
        - |-
          while true :; do printf '.'; sleep 100; done
      env:
      - name: CERT_NAME
        value: /etc/secret/CERT_NAME
      - name: dns_cloudflare_email
        value: /etc/secret/dns_cloudflare_email
      - name: dns_cloudflare_api_key
        value: /etc/secret/dns_cloudflare_api_key
      - name: LETSENCRYPT_DATA_DIR
        value: /etc/secret/LETSENCRYPT_DATA_DIR
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secret/credentials.json
      volumeMounts:
      - name: letsencryptdata
        mountPath: "/data"
      - name: secret
        mountPath: "/etc/secret"
        readOnly: true
  volumes:
    - name: letsencryptdata
      persistentVolumeClaim:
        claimName: bs-letsencrypt-disk
    - name: secret
      secret:
        secretName: letsencryptit