kind: Pod
apiVersion: v1
metadata:
  name: letsencryptit-cli
  labels:
    app: letsencryptit-cli 
spec:
  containers:
    - name: letsencryptit-cli-container
      image: index.docker.io/larssb/letsencryptit
      volumeMounts:
      - name: letsencryptdata
        mountPath: "/data"
      command: ["python3", "-c $'import time\\nwhile (True):\\n    print(\".\");time.sleep(5);'"]
  volumes:
    - name: letsencryptdata
      persistentVolumeClaim:
        claimName: bs-letsencrypt-disk